import { writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { argv } from 'node:process';
import { fileURLToPath } from 'node:url';

import { resolveSelectedCapabilities, resolveSurfaceModules } from '../../dist/index.js';

import { activation, capabilitiesDir, seed, surface, workspaceRoot } from './composition.mjs';

// The build-time step. It runs the framework-free composition once — discovery,
// dependency-graph selection, single-provider resolution — and CODE-GENERATES a
// module of *static* imports via the shared `resolveSurfaceModules` seam. The
// injected set is fixed and visible at build time; nothing is decided at runtime.
const srcDir = dirname(fileURLToPath(import.meta.url));

export function generate() {
  const active = resolveSelectedCapabilities({ workspaceRoot, capabilitiesDir, seed });
  const modules = resolveSurfaceModules(active, surface, activation);

  const entries = modules.map((module) => {
    const moduleFile = join(module.capability.directory, 'src/server.mjs');
    const importPath = relative(srcDir, moduleFile).split('\\').join('/');
    return { id: module.capability.id, exportName: module.exportName, importPath };
  });

  const generated = `// GENERATED by build.mjs - do not edit.
// The injected server capabilities are frozen here at build time.
${entries.map((entry) => `import { ${entry.exportName} } from '${entry.importPath}';`).join('\n')}

export const serverCapabilities = [${entries.map((entry) => entry.exportName).join(', ')}];
export const injectedIds = ${JSON.stringify(entries.map((entry) => entry.id))};
`;

  const outFile = join(srcDir, 'capabilities.generated.mjs');
  writeFileSync(outFile, generated);
  return { outFile, ids: entries.map((entry) => entry.id) };
}

if (fileURLToPath(import.meta.url) === argv[1]) {
  const { ids } = generate();
  console.log('build-time: generated a fixed set ->', ids);
}
