/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechRouteImport } from './../capabilities/web/src/routes/tech'
import { Route as IndexRouteImport } from './../capabilities/shops/src/routes/index'
import { Route as ShopsDotstationeryRouteImport } from './../capabilities/shop-stationery/src/routes/shops.stationery'
import { Route as ShopsDotcoffeeRouteImport } from './../capabilities/shop-coffee/src/routes/shops.coffee'
import { Route as ProvidersDotpaymentProviderStripeDotcheckoutRouteImport } from './../capabilities/payment-provider-stripe/src/routes/providers.payment-provider-stripe.checkout'

const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsDotstationeryRoute = ShopsDotstationeryRouteImport.update({
  id: '/shops/stationery',
  path: '/shops/stationery',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsDotcoffeeRoute = ShopsDotcoffeeRouteImport.update({
  id: '/shops/coffee',
  path: '/shops/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersDotpaymentProviderStripeDotcheckoutRoute =
  ProvidersDotpaymentProviderStripeDotcheckoutRouteImport.update({
    id: '/providers/payment-provider-stripe/checkout',
    path: '/providers/payment-provider-stripe/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tech': typeof TechRoute
  '/shops/coffee': typeof ShopsDotcoffeeRoute
  '/shops/stationery': typeof ShopsDotstationeryRoute
  '/providers/payment-provider-stripe/checkout': typeof ProvidersDotpaymentProviderStripeDotcheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tech': typeof TechRoute
  '/shops/coffee': typeof ShopsDotcoffeeRoute
  '/shops/stationery': typeof ShopsDotstationeryRoute
  '/providers/payment-provider-stripe/checkout': typeof ProvidersDotpaymentProviderStripeDotcheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tech': typeof TechRoute
  '/shops/coffee': typeof ShopsDotcoffeeRoute
  '/shops/stationery': typeof ShopsDotstationeryRoute
  '/providers/payment-provider-stripe/checkout': typeof ProvidersDotpaymentProviderStripeDotcheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tech'
    | '/shops/coffee'
    | '/shops/stationery'
    | '/providers/payment-provider-stripe/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tech'
    | '/shops/coffee'
    | '/shops/stationery'
    | '/providers/payment-provider-stripe/checkout'
  id:
    | '__root__'
    | '/'
    | '/tech'
    | '/shops/coffee'
    | '/shops/stationery'
    | '/providers/payment-provider-stripe/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TechRoute: typeof TechRoute
  ShopsDotcoffeeRoute: typeof ShopsDotcoffeeRoute
  ShopsDotstationeryRoute: typeof ShopsDotstationeryRoute
  ProvidersDotpaymentProviderStripeDotcheckoutRoute: typeof ProvidersDotpaymentProviderStripeDotcheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/stationery': {
      id: '/shops/stationery'
      path: '/shops/stationery'
      fullPath: '/shops/stationery'
      preLoaderRoute: typeof ShopsDotstationeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/coffee': {
      id: '/shops/coffee'
      path: '/shops/coffee'
      fullPath: '/shops/coffee'
      preLoaderRoute: typeof ShopsDotcoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/payment-provider-stripe/checkout': {
      id: '/providers/payment-provider-stripe/checkout'
      path: '/providers/payment-provider-stripe/checkout'
      fullPath: '/providers/payment-provider-stripe/checkout'
      preLoaderRoute: typeof ProvidersDotpaymentProviderStripeDotcheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TechRoute: TechRoute,
  ShopsDotcoffeeRoute: ShopsDotcoffeeRoute,
  ShopsDotstationeryRoute: ShopsDotstationeryRoute,
  ProvidersDotpaymentProviderStripeDotcheckoutRoute:
    ProvidersDotpaymentProviderStripeDotcheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
